import NavBar from '../components/navbar';

export const metadata = {
  title: 'IWM',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children, disableNavBar }) {
  const isNavBarEnabled = !disableNavBar;

  return (
    <html lang="en">
      <body>
        {isNavBarEnabled && <NavBar />}
        <div style={{width:'5rem'}}></div>
        {children}
        <div style={{width:'5rem'}}></div>
    </body>
    </html>
  );
}
